# Generated by Django 4.2.24 on 2025-09-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_singleforminput"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forminput",
            name="ageranges",
            field=models.CharField(default="-1", max_length=4),
        ),
        migrations.AlterField(
            model_name="forminput",
            name="gp",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="forminput",
            name="recommendations",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="singleforminput",
            name="gp",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="singleforminput",
            name="recommendations",
            field=models.JSONField(default=list),
        ),
    ]
